---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1mrznl77u244lz33xamm6948kvm27rd92xz4rqr7ulpg6evjvqspquw9nux
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1mrznl77u244lz33xamm6948kvm27rd92xz4rqr7ulpg6evjvqspquw9nux
