---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: networking
spec:
  chart:
    spec:
      # renovate: registryUrl=https://charts.kubito.dev
      chart: cloudflared
      version: 1.0.3
      sourceRef:
        kind: HelmRepository
        name: kubito
        namespace: flux-system
      interval: 5m
  interval: 15m
  maxHistory: 2
  timeout: 20m
  install:
    remediation:
      retries: 300
  upgrade:
    remediation:
      retries: 300
  values:
    image:
      repository: ghcr.io/milgradesec/cloudflared
      tag: 2023.5.0
    replicaCount: 1
    tunnelID: ${SECRET_CLOUDFLARE_TUNNEL_ID}
    existingSecret: cloudflare-tunnel-credentials
    warpRouting: true
    ingress:
      - hostname: "znc.${SECRET_DOMAIN}"
        service: tcp://ingress-nginx-controller.networking
        originRequest:
          proxyType: socks
      - hostname: "*.${SECRET_DOMAIN}"
        service: https://ingress-nginx-controller.networking
        originRequest:
          noTLSVerify: true
      - service: http_status:404
