---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bitlbee
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
    image:
      repository: ezkrg/bitlbee-libpurple
      tag: latest
    service:
      main:
        ports:
          http:
            port: 6667
            protocol: TCP
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 96Mi
    persistence:
      config:
        enabled: true
        existingClaim: bitlbee-config
        mountPath: /var/lib/bitlbee
    initContainers:
      ownership:
        image: alpine:3
        command: ['bin/sh', '-c', 'chown -R 101:101 /var/lib/bitlbee']
        volumeMounts:
          - name: config
            mountPath: /var/lib/bitlbee
