---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      defaultClassReplicaCount: 1
    defaultSettings:
      #backupTarget: s3://longhorn@minio/backups
      #backupTargetCredentialSecret: longhorn-backup
      #defaultReplicaCount: 2
      #defaultLonghornStaticStorageClass: longhorn
    ingress:
      enabled: true
      host: "longhorn.${SECRET_DOMAIN}"
      path: /
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: letsencrypt-production
        hajimari.io/enable: "true"
        hajimari.io/icon: cow
        hajimari.io/group: storage
        hajimari.io/appName: longhorn
