---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: znc-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
