---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: znc
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      replicas: 1
      strategy: Recreate
    image:
      repository: znc
      tag: 1.8.2
    initContainers:
      config:
        name: init-config
        image: znc:1.8.2
        command: ['/bin/sh', '-c', "until [ -f /znc-data/configs/znc.conf ]; do echo waiting for znc.conf; sleep 2; done"]
        volumeMounts:
          - mountPath: /znc-data
            name: config
    service:
      main:
        ports:
          http:
            port: 8080
            protocol: TCP
          irc:
            port: 6667
            primary: false
            protocol: TCP
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com"
          hajimari.io/enable: "true"
          hajimari.io/icon: "video-input-antenna"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: 6667
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 96Mi
    persistence:
      config:
        enabled: true
        existingClaim: znc-config
        mountPath: /znc-data
