image:
  repository: znc
  tag: 1.8.2
initContainers:
  config:
    name: init-config
    image: znc:1.8.2
    command: ['/bin/sh', '-c', "until [ -f /znc-data/configs/znc.conf ]; do echo waiting for znc.conf; sleep 2; done"]
    volumeMounts:
      - mountPath: /znc-data
        name: znc-config
service:
  main:
    ports:
      http:
        port: 6667
        protocol: TCP
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 96Mi
persistence:
  config:
    enabled: true
    existingClaim: znc-config
    mountPath: /znc-data
